### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [BuntingLabs/buntinglabs-qgis-plugin#1]
Please update the homepage link in metadata.txt to reference a link that is specific to plugin usage

**Comment by brendanashworth** [comment]
Thanks @NyakudyaA for the review, just added a link to [the new plugin page](https://buntinglabs.com/solutions/ai-vectorizer-qgis-plugin) in https://github.com/BuntingLabs/buntinglabs-qgis-plugin/commit/97fb4a1fd7319755125db02a4076115c501505a9.

Anything else I should fix?
