### ISSUE TITLE
Document where to find the icon button.

### ISSUE THREAD

**Issue by barryrowlingson** [BuntingLabs/buntinglabs-qgis-plugin#10]
I just spent twenty minutes trying to find the icon button. I have a rich UI set up in QGIS with lots of plugins and half a screen full of toolbars (slight exaggeration) and couldn't find the button to run the digitizer! Eventually went to the code and the docs for `iface.addToolBarIcon` to discover it goes into the "Plugins" toolbar, which I had set disabled and invisible.

All worked fine from there but mentioning the toolbar in the docs and demos would help greatly!

**Comment by brendanashworth** [comment]
@barryrowlingson thanks for bringing this up — I'm sure the toolbars is no exaggeration!

I'm going to both document it _and_ show a warning on startup if the plugins toolbar is hidden/invisible. Do you think that would have helped you? Sorry it wasn't easy to get started.

**Comment by barryrowlingson** [comment]
That sounds ideal. Some plugins will also put their button actions in their menu entry (where you have the way to get to the settings dialog). I'm not sure what the standard guidelines for toolbars are now, the other option is to have a dedicated toolbar for your action and then it would show in the View... Toolbars list as "AI Digitiser" or similar, but does seem over the top for one button...

**Comment by brendanashworth** [comment]
@barryrowlingson thank you so much for the helpful ideas! I've:

1. added a warning (with tutorial link) that's shown if the plugin toolbar is invisible https://github.com/BuntingLabs/buntinglabs-qgis-plugin/commit/3ded769591451ba9050f2ef6f117fb194fb1510e
2. added "vectorize with AI" button action to the plugin dropdown menu if you want to keep the plugin toolbar hidden https://github.com/BuntingLabs/buntinglabs-qgis-plugin/commit/df8a0be33dcdd156567e36552f47ede626d310f4
3. and also updated the in-plugin instructions and README to mention the plugin toolbar by name

maybe someday we'll have more tools to make our own toolbar 😄
