### ISSUE TITLE
not able to create account on BuntingLabs

### ISSUE THREAD

**Issue by AnandMalik** [BuntingLabs/buntinglabs-qgis-plugin#7]
tried many times after installing the plugin in qgis. but there is some issue with website. as it not oping up. hence not able to login and create account / verify and not able to work with AI digitization. please fix. Thank you . Anand

**Comment by brendanashworth** [comment]
hi @AnandMalik thanks for creating an issue, I'm going to look into this!

**Comment by brendanashworth** [comment]
@AnandMalik would you mind emailing me (`brendan` at `buntinglabs` dot `com`) with the email address you tried to sign up?

**Comment by AnandMalik** [comment]
Thank you very much for considering my threat i am using my official email id anandmalik@ss.du.ac.in

**Comment by brendanashworth** [comment]
seems like it's working for you now, let me know if there's anything else I can help with!
