### ISSUE TITLE
Autocomplete server fails

### ISSUE THREAD

**Issue by HRGISolutionsInc** [BuntingLabs/buntinglabs-qgis-plugin#8]
Hi there,

When trying to digitize a shape, I get this error and it doesn't work:

2024-05-27T14:36:48     CRITICAL    AI Vectorizer : Autocomplete server failed SSL Certificate Verification

Any clues?

Many thanks!

**Comment by HRGISolutionsInc** [comment]
Worked on another computer at work. Problem must be at my end. But could be looked into nonetheless.
Thanks!

**Comment by brendanashworth** [comment]
@HRGISolutionsInc thanks for pinging me on this — I've seen this error a few times but have never successfully fixed it for anyone. It seems dependent on the computer you're connecting from as our certificates are valid and renewed. Sorry I don't have good advice... not sure what causes this issue.
